#!/bin/bash

DO_EXT=no
DO_LIST_VER=yes-nocd
DO_MOD_VER=no
DO_SHELL=yes
DO_MODE=s
DO_WARNING_EXTERNAL=yes
SCBI_FILTER=all

SHL_MODULE=""
SHL_VARIANT=""
SHL_KIND=""

############################################## shl-usage
#
#  Display script usage
#
function shl-usage()
{
    echo
    echo SCBI-SHELL $SCBI_VERSION
    echo
    echo $0 shell [options] plug-in1 [plug-in2...]

    echo ""
    echo "   -h | --help             this help message"
    echo "   -v | --version          display driver & plug-ins versions"
    echo "      | --plugins=<dir>    specify the plugins' directory"
    echo "   -e | --env=<name>       environment file ~/.scbi-<name>"
    echo "      | --build-dir=<dir>  the root build directory."
    echo "      | --mode:n           start a shell with module's environment"
    echo "      | --run=\"cmd arg\"    run command in module's environment"
    echo "      | --stat             display some status of current setup"
}
#  setup for SCBI shell & command spawn

############################## shl-setup-env

function shl-setup-env()
{
    local MODREF=$1
    local MODULES=( $2 )
    local DOCD=$3

    if [[ "$SCBI_HOST" != "$SCBI_TARGET" ]]; then
        target-env $SCBI_BDIR/install $SCBI_TARGET
    fi

    for M in ${MODULES[*]}; do
        handle-env "@root" $M
        handle-module-env "@root" $M env
    done

    local module_info=()
    get-module-ref module_info $MODREF
    SHL_MODULE=${module_info[0]}
    SHL_VARIANT=${module_info[1]}
    SHL_KIND=${module_info[2]}

    export SCBI_SHELL=$DO_MODE:$SHL_MODULE

    #  If docd set (no cwd sub-option specified), we are moving into
    #  the module's build directory. In this mode we not only want the
    #  environment of all dependencies to be set but we also want the
    #  build environment of the root module to be set.

    [[ $DOCD == yes-dev ]] &&
        {
            handle-build-depends-env "@root" $MODREF
            handle-module-env "@root" $MODREF build-env
        }

    [[  $DOCD == yes-tests ]] &&
        handle-tests-depends-env "@root" $MODREF
}

############################## shl-run-shell

function shl-run-shell()
{
    local TARGET=$1
    local MODULES=( $2 )
    local DOCD=$3

    if [[ -z $SHELL ]]; then
        echo \$SHELL is not defined, cannot spawn a shell
        exit 1
    fi

    curcd=$(pwd)

    local MODREF=${MODULES[-1]}
    local DIR=""

    shl-setup-env $MODREF "${MODULES[*]}" $DOCD

    #  If docd set (no cwd sub-option specified), we are moving into
    #  the module's build directory. In this mode we not only want the
    #  environment of all dependencies to be set but we also want the
    #  build environment of the root module to be set.

    if [[ $DOCD == no ]]; then
        cd $curcd
    elif [[ ${SHL_KIND} == DEV ]] || [[ $DOCD == yes-dev ]]; then
        DIR=$(get-vcs-dir ${SHL_MODULE}:dev)
        if [[ ! -d $DIR ]]; then
            DIR=""
            elog ${SHL_MODULE} no user checkout directory $DIR
        fi
    else
        DIR=$(get-build-dir $TARGET $MODREF)
    fi

    [[ -n $DIR ]] &&
        {
            local PFX=${curcd#$DIR}
            [[ $PFX == $curcd ]] &&
                cd $DIR
        }

    #  Exports all functions into the bash sub-shell
    eval "$(declare -F | sed -e 's/-f /-fx /')"
    $SHELL
}

############################## shl-run-command

function shl-run-command()
{
    local TARGET=$1
    local MODULES=( $2 )
    local CMD="$3"
    local DOCD=$4

    if [[ -z $SHELL ]]; then
        echo \$SHELL is not defined, cannot spawn a shell
        exit 1
    fi

    local MODREF=${MODULES[-1]}

    shl-setup-env $MODREF "${MODULES[*]}" $DOCD

    if [[ -z $CMD ]]; then
        local PREFIX=$SCBI_BDIR/${SHL_MODULE}/$TARGET-${SHL_VARIANT}/install
        # CMD is not specified, try using the one defined in
        # the plug-in itself.
        for C in $(plugin-call-variant-hooks ${SHL_MODULE} run \
                                             $PREFIX $TARGET ${SHL_VARIANT});
        do
            CMD+="$C "
        done

        if [[ -z $CMD ]]; then
            elog ${SHL_MODULE} no command specified for run option
        fi
    fi

    #  Exports all functions into the bash sub-shell
    eval "$(declare -F | sed -e 's/-f /-fx /')"

    $SHELL -c "$CMD"
}

#  Check that this script has properly been called by scbi main
#  script.

if [[ $1 == "subcommand" ]]; then
    shift
else
    echo "error: use scbi shell [options]"
    exit 1
fi

#  Parse run without getopt as an argument to run can have spaces

SCBIOPTS=()

while [[ $# -gt 0 ]]; do
    case $1 in
        --run=*)
            DO_RUN=yes
            DO_RUN_CMD=${1/*=/}
            ;;
        --run)
            DO_RUN=yes
            DO_RUN_CMD=""
            ;;
        (-*)
            SCBIOPTS+=( $1 )
            ;;
        (*)
            ;;
    esac
    shift
done

OPTFILE=$(mktemp)

ALLOPTS=$(getopt -u -o kld \
                 -l mode:use,mode:dev,mode:tests,mode:sb,mode:sandbox \
                 -- ${SCBIOPTS[*]} 2> $OPTFILE)

if [[ $? != 0 ]]; then
    cat $OPTFILE
    echo try \"scbi shell --help\" for more information.
    rm -f $OPTFILE
    exit 1
fi

set -- $ALLOPTS

while [[ $# -gt 0 ]]; do
    case $1 in
        --mode:sb|--mode:sandbox)
            DO_SHELL=yes
            DO_MODE=s
            ;;
        --mode:dev)
            DO_SHELL=yes-dev
            DO_MODE=d
            ;;
        --mode:tests)
            DO_SHELL=yes-tests
            DO_MODE=t
            ;;
        --mode:use)
            DO_SHELL=yes-nocd
            DO_MODE=u
            ;;
        (--)
            ;;
        (*)
            ;;
        (-*)
            echo "$0: error - unrecognized option $1" 1>&2; exit 1
            sto-usage
            ;;
    esac
    shift
done

if [[ $DO_HELP == yes ]]; then
    shl-usage
    exit 0
fi

if [[ -z ${SCBI_MODULES[*]} ]]; then
    echo "error: shell/run commands need a plug-in, see scbi shell --help"
    exit 0
fi

#  If a run is requested

if [[ $DO_RUN == yes ]]; then
    shl-run-command $SCBI_TARGET "${SCBI_MODULES[*]}" "$DO_RUN_CMD" $DO_SHELL
    exit 0
fi

#  If a shell is requested

if [[ $DO_SHELL == yes-nocd ]]; then
    shl-run-shell $SCBI_TARGET "${SCBI_MODULES[*]}" no
    exit 0
fi

if [[ $DO_SHELL =~ yes ]]; then
    shl-run-shell $SCBI_TARGET "${SCBI_MODULES[*]}" $DO_SHELL
    exit 0
fi

#  No parameter
shl-usage
