#!/bin/bash

function run-test()
{
    local TEST=$1

    (
        cp drivers/$TEST . && source ./$TEST
        rm -f $TEST
    )
}

./clean

export CDPATH=

# copy scripts
cp ../scbi .
cp ../scripts.d/[2-9]* scripts.d/

# the repository directory
export TESTREPOS=$PWD/.root/repos

# kill mail for testing
export EMAIL_NOTIFICATION=no

# be sure the global install directory exists
mkdir -p $PWD/.root/builds/install

# create the log dirs
mkdir -p $PWD/logs

if [ -z $1 ]; then
    TESTS='drivers/test*'
else
    TESTS=drivers/$1
fi

for file in $TESTS; do
    bfile=$(basename $file)
    echo -n "========== $bfile "
    run-test $bfile 2>&1 > logs/$bfile.log

    sed -i 's/[0-9]/x/g' logs/$bfile.log

    diff -q logs/$bfile.log expected/$bfile.exp 2>&1 > /dev/null

    if [ $? == 0 ]; then
        echo OK
    else
        echo NOK
    fi
done
