#!/bin/bash

export LANG=C

function run-test()
{
    local TEST=$1

    (
        cp drivers/$TEST . && source ./$TEST
        rm -f $TEST
    )
}

./clean

export CDPATH=

# copy scripts
cp ../scbi .
cp ../scripts.d/[1-9]* scripts.d/
cp ../scripts.d/.pkgs-* scripts.d/

# patch rsync to use safe mode (checksum) as the tests repositories are small,
# and has some files with same time-stamp.

sed -i 's/rsync -a/rsync -a -c/g' scripts.d/7_modgen
sed -i 's/dlog/ilog/g' scripts.d/7_modgen

mkdir -p .root/.patches

# the repository directory
export TESTREPOS=$PWD/.root/repos

# kill mail for testing
export EMAIL_NOTIFICATION=no

# be sure the global install directory exists
mkdir -p $PWD/.root/builds/install

# create the log dirs
mkdir -p $PWD/logs

if [ -z $1 ]; then
    TESTS='drivers/test*'
else
    TESTS="drivers/$*"
fi

for file in $TESTS; do
    # copy/reset patches each time as some drivers
    # are changing them for testing purpose.
    cp .root/repos/*.patch .root/.patches/

    # clean build directory to ensure each run are independent
    rm -fr .root/builds

    bfile=$(basename $file)
    echo -n "========== $bfile "
    run-test $bfile 2>&1 > logs/$bfile.log

    sed -i 's/[0-9]/x/g;${/^$/d;}' logs/$bfile.log

    diff -q logs/$bfile.log expected/$bfile.exp 2>&1 > /dev/null

    if [ $? == 0 ]; then
        echo OK
    else
        echo NOK
    fi
done
