no variant
xxxx/xx/xx xx:xx:xx : Building confopts [default] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : config starting
call -DcommonX -DcommonY
xxxx/xx/xx xx:xx:xx : config completed
xxxx/xx/xx xx:xx:xx : End Building confopts [default] (master)

variant vara
xxxx/xx/xx xx:xx:xx : Building confopts [vara] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : config [vara] starting
call -DcommonX -DcommonY -DvaraA
xxxx/xx/xx xx:xx:xx : config [vara] completed
xxxx/xx/xx xx:xx:xx : End Building confopts [vara] (master)

variant varb
xxxx/xx/xx xx:xx:xx : Building confopts [varb] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : config [varb] starting
call -DcommonX -DcommonY -DvarbA -DvarbB
xxxx/xx/xx xx:xx:xx : config [varb] completed
xxxx/xx/xx xx:xx:xx : End Building confopts [varb] (master)

variant vara and varb
xxxx/xx/xx xx:xx:xx : Building confopts [vara varb] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : config [vara varb] starting
call -DcommonX -DcommonY -DvaraA -DvarbA -DvarbB
xxxx/xx/xx xx:xx:xx : config [vara varb] completed
xxxx/xx/xx xx:xx:xx : End Building confopts [vara varb] (master)
