========== build/install libx
xxxx/xx/xx xx:xx:xx : Building libx [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : config starting
xxxx/xx/xx xx:xx:xx : config completed
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : tests starting
main
libb.B master (default)
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building libx [default] (master)

========== build/install libx/variant
xxxx/xx/xx xx:xx:xx : Building libx [variantx] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : variantx-config starting
xxxx/xx/xx xx:xx:xx : variantx-config completed
xxxx/xx/xx xx:xx:xx : build [variantx] starting
xxxx/xx/xx xx:xx:xx : build [variantx] completed
xxxx/xx/xx xx:xx:xx : install [variantx] starting
xxxx/xx/xx xx:xx:xx : install [variantx] completed
xxxx/xx/xx xx:xx:xx : tests [variantx] starting
main
libb.B master (variantx)
xxxx/xx/xx xx:xx:xx : tests [variantx] completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building libx [variantx] (master)

========== install libx
xxxx/xx/xx xx:xx:xx : Building libx [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : tests starting
main
libb.B master (default)
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building libx [default] (master)

========== build/install libx/variant vx
xxxx/xx/xx xx:xx:xx : Building libx [variantx] (vx.x)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : variantx-config starting
xxxx/xx/xx xx:xx:xx : variantx-config completed
xxxx/xx/xx xx:xx:xx : build [variantx] starting
xxxx/xx/xx xx:xx:xx : build [variantx] completed
xxxx/xx/xx xx:xx:xx : install [variantx] starting
xxxx/xx/xx xx:xx:xx : install [variantx] completed
xxxx/xx/xx xx:xx:xx : tests [variantx] starting
main
libb.B vx (variantx)
xxxx/xx/xx xx:xx:xx : tests [variantx] completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building libx [variantx] (vx.x)

========== build/install libx/variant tag vx.x.x
xxxx/xx/xx xx:xx:xx : Building libx [variantx] (vx.x.x)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : variantx-config starting
xxxx/xx/xx xx:xx:xx : variantx-config completed
xxxx/xx/xx xx:xx:xx : build [variantx] starting
xxxx/xx/xx xx:xx:xx : build [variantx] completed
xxxx/xx/xx xx:xx:xx : install [variantx] starting
xxxx/xx/xx xx:xx:xx : install [variantx] completed
xxxx/xx/xx xx:xx:xx : tests [variantx] starting
main
libb.A master (variantx)
xxxx/xx/xx xx:xx:xx : tests [variantx] completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building libx [variantx] (vx.x.x)

========== just test libx/variant tag vx.x.x
xxxx/xx/xx xx:xx:xx : Building libx [variantx] (vx.x.x)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : tests [variantx] starting
main
libb.A master (variantx)
xxxx/xx/xx xx:xx:xx : tests [variantx] completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building libx [variantx] (vx.x.x)
