========== build/install libx
xxxx/xx/xx xx:xx : Building libx-default
xxxx/xx/xx xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : get sources from git
xxxx/xx/xx xx:xx : config starting
xxxx/xx/xx xx:xx : config completed
xxxx/xx/xx xx:xx : build starting
xxxx/xx/xx xx:xx : build completed
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
libb.B master (default)
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

========== build/install libx/variant
xxxx/xx/xx xx:xx : Building libx-variantx
xxxx/xx/xx xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : variantx-config starting
xxxx/xx/xx xx:xx : variantx-config completed
xxxx/xx/xx xx:xx : build starting
xxxx/xx/xx xx:xx : build completed
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
libb.B master (variantx)
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

========== install libx
xxxx/xx/xx xx:xx : Building libx-default
xxxx/xx/xx xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
libb.B master (default)
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

========== build/install libx/variant vx
xxxx/xx/xx xx:xx : Building libx-variantx
xxxx/xx/xx xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : get sources from git
xxxx/xx/xx xx:xx : variantx-config starting
xxxx/xx/xx xx:xx : variantx-config completed
xxxx/xx/xx xx:xx : build starting
xxxx/xx/xx xx:xx : build completed
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
libb.B vx (variantx)
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

========== build/install libx/variant tag vx.x.x
xxxx/xx/xx xx:xx : Building libx-variantx
xxxx/xx/xx xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : get sources from git
xxxx/xx/xx xx:xx : variantx-config starting
xxxx/xx/xx xx:xx : variantx-config completed
xxxx/xx/xx xx:xx : build starting
xxxx/xx/xx xx:xx : build completed
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
libb.A master (variantx)
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

========== just test libx/variant tag vx.x.x
xxxx/xx/xx xx:xx : Building libx-variantx
xxxx/xx/xx xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx : tests starting
main
libb.A master (variantx)
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

