============= x
xxxx/xx/xx xx:xx:xx : Building varhook [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : config starting
xxxx/xx/xx xx:xx:xx : config completed
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : End Building varhook [default] (master)

============= x
xxxx/xx/xx xx:xx:xx : Building varhook [mpi] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : config [mpi] starting
xxxx/xx/xx xx:xx:xx : config [mpi] completed
xxxx/xx/xx xx:xx:xx : build [mpi] starting
xxxx/xx/xx xx:xx:xx : build [mpi] completed
xxxx/xx/xx xx:xx:xx : install [mpi] starting
xxxx/xx/xx xx:xx:xx : install [mpi] completed
xxxx/xx/xx xx:xx:xx : End Building varhook [mpi] (master)

============= x
xxxx/xx/xx xx:xx:xx : Building varhook [mpi openmp] (dev)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : config [mpi openmp] starting
xxxx/xx/xx xx:xx:xx : config [mpi openmp] completed
xxxx/xx/xx xx:xx:xx : build [mpi openmp] starting
xxxx/xx/xx xx:xx:xx : build [mpi openmp] completed
xxxx/xx/xx xx:xx:xx : install [mpi openmp] starting
xxxx/xx/xx xx:xx:xx : install [mpi openmp] completed
xxxx/xx/xx xx:xx:xx : End Building varhook [mpi openmp] (dev)

.root/builds/.logs/xxx_xx-linux-gnu-varhook-mpi-config.log:@@@ MPI
.root/builds/.logs/xxx_xx-linux-gnu-varhook-mpi.openmp-config.log:@@@ MPI
.root/builds/.logs/xxx_xx-linux-gnu-varhook-mpi.openmp-config.log:@@@ OpenMP
