========== libx patched version
xxxx/xx/xx xx:xx : Building libx-default
xxxx/xx/xx xx:xx : target xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : get sources from git
xxxx/xx/xx xx:xx : build starting
xxxx/xx/xx xx:xx : build completed
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
liba.C patched version
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

========== libx standard version
xxxx/xx/xx xx:xx : Building libx-default
xxxx/xx/xx xx:xx : target xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : build starting
xxxx/xx/xx xx:xx : build completed
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
liba.C master
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

========== libx patych again
xxxx/xx/xx xx:xx : Building libx-default
xxxx/xx/xx xx:xx : target xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : build starting
xxxx/xx/xx xx:xx : build completed
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
liba.C patched version
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

