========== OPT-A
xxxx/xx/xx xx:xx:xx : Building mspace [opta] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : opta-config starting
xxxx/xx/xx xx:xx:xx : opta-config completed
xxxx/xx/xx xx:xx:xx : End Building mspace [opta] (master)

A one
B two
C -DLIB=-L/usr/lib -lmpi_cxx -lmpi
========== OPT-B
xxxx/xx/xx xx:xx:xx : Building mspace [optb] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : optb-config starting
xxxx/xx/xx xx:xx:xx : optb-config completed
xxxx/xx/xx xx:xx:xx : End Building mspace [optb] (master)

A one
B two
C -DLIB=-lz1 -lz2 -lz3
========== OPT-A + OPT-B
xxxx/xx/xx xx:xx:xx : Building mspace [opta optb] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : config [opta optb] starting
xxxx/xx/xx xx:xx:xx : config [opta optb] completed
xxxx/xx/xx xx:xx:xx : End Building mspace [opta optb] (master)

A one
B two
C -DLIB=-L/usr/lib -lmpi_cxx -lmpi
A one
B two
C -DLIB=-lz1 -lz2 -lz3
A one
B two
C -DLIB=-L/usr/lib -lmpi_cxx -lmpi
A one
B two
C -DLIB=-lz1 -lz2 -lz3
