xxxx/xx/xx xx:xx:xx : Building testxx-default (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : setup starting
xxxx/xx/xx xx:xx:xx : setup completed
xxxx/xx/xx xx:xx:xx : config starting
xxxx/xx/xx xx:xx:xx : config completed
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : End building testxx-default

in config
ROOT_DIR /this/is/it
ABC_ROOT /perfect/here
PATH /tmp:/bin:/usr/bin
CONFxx two:one
in build
ROOT_DIR /this/is/it
ABC_ROOT /perfect/here
PATH /tmp:/bin:/usr/bin
CONFxx two:one
in install
ROOT_DIR /this/is/it
ABC_ROOT /perfect/here
PATH /tmp:/bin:/usr/bin
CONFxx two:one
