=============== A AUTO on command line - no native
xxxx/xx/xx xx:xx:xx : autovarA (FAILED) autovarA auto mode must define a native variant
=============== A AUTO on plan - no native
xxxx/xx/xx xx:xx:xx : autovarA (FAILED) autovarA auto mode must define a native variant
=============== B AUTO on command line
xxxx/xx/xx xx:xx:xx : dependency amoeba not installed
xxxx/xx/xx xx:xx:xx : autovarB using standard variant

xxxx/xx/xx xx:xx:xx : Building autovarB [default] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : config starting
xxxx/xx/xx xx:xx:xx : config completed
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : skip global install
xxxx/xx/xx xx:xx:xx : End Building autovarB [default] (master)

=============== B AUTO on plan
xxxx/xx/xx xx:xx:xx : dependency amoeba not installed
xxxx/xx/xx xx:xx:xx : autovarB using standard variant

xxxx/xx/xx xx:xx:xx : Building autovarB [default] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : skip global install
xxxx/xx/xx xx:xx:xx : End Building autovarB [default] (master)

=============== C AUTO on command line
xxxx/xx/xx xx:xx:xx : unknown dependency shouldnotexist-dev
xxxx/xx/xx xx:xx:xx : autovarC using standard variant

xxxx/xx/xx xx:xx:xx : Building autovarC [default] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no sources (vcs or tar)
xxxx/xx/xx xx:xx:xx : config starting
xxxx/xx/xx xx:xx:xx : config completed
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : skip global install
xxxx/xx/xx xx:xx:xx : End Building autovarC [default] (master)
