============ run one : build
xxxx/xx/xx xx:xx:xx : Building inhnat [native] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : native-config starting
xxxx/xx/xx xx:xx:xx : native-config completed
xxxx/xx/xx xx:xx:xx : native-build starting
xxxx/xx/xx xx:xx:xx : native-build completed
xxxx/xx/xx xx:xx:xx : native-install starting
xxxx/xx/xx xx:xx:xx : native-install completed
xxxx/xx/xx xx:xx:xx : skip global install
xxxx/xx/xx xx:xx:xx : End Building inhnat [native] (master)

xxxx/xx/xx xx:xx:xx : Building lib3 [default] (v1.2)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : get sources from tar
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building lib3 [default] (v1.2)

============ run two : nothing to do
xxxx/xx/xx xx:xx:xx : Building inhnat [native] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : skip global install
xxxx/xx/xx xx:xx:xx : End Building inhnat [native] (master)

xxxx/xx/xx xx:xx:xx : Building lib3 [default] (v1.2)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building lib3 [default] (v1.2)
