========== deps A
xxxx/xx/xx xx:xx:xx : need building recb, current version latest

xxxx/xx/xx xx:xx:xx : need building recc, current version latest

xxxx/xx/xx xx:xx:xx : need building reca, current version latest
xxxx/xx/xx xx:xx:xx : skip reca, already handled

xxxx/xx/xx xx:xx:xx : Building recc [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : recc (FAILED) recursive dependencies detected
xxxx/xx/xx xx:xx:xx : recc (FAILED) . recc -> reca
xxxx/xx/xx xx:xx:xx : recc (FAILED) . reca -> recb
xxxx/xx/xx xx:xx:xx : recc (FAILED) . recb -> recc
========== list-depends A
xxxx/xx/xx xx:xx:xx : reca (FAILED) recursive dependencies detected
xxxx/xx/xx xx:xx:xx : reca (FAILED) . reca -> recb
xxxx/xx/xx xx:xx:xx : reca (FAILED) . recb -> recc
xxxx/xx/xx xx:xx:xx : reca (FAILED) . recc -> reca
========== list-depends B
xxxx/xx/xx xx:xx:xx : recb (FAILED) recursive dependencies detected
xxxx/xx/xx xx:xx:xx : recb (FAILED) . recb -> recc
xxxx/xx/xx xx:xx:xx : recb (FAILED) . recc -> reca
xxxx/xx/xx xx:xx:xx : recb (FAILED) . reca -> recb
