====================== testxx
xxxx/xx/xx xx:xx:xx : Building testxx [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : pre-setup starting
xxxx/xx/xx xx:xx:xx : pre-setup completed
xxxx/xx/xx xx:xx:xx : config starting
xxxx/xx/xx xx:xx:xx : config completed
xxxx/xx/xx xx:xx:xx : post-config starting
xxxx/xx/xx xx:xx:xx : post-config completed
xxxx/xx/xx xx:xx:xx : pre-build starting
xxxx/xx/xx xx:xx:xx : pre-build completed
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : post-build starting
xxxx/xx/xx xx:xx:xx : post-build completed
xxxx/xx/xx xx:xx:xx : pre-install starting
xxxx/xx/xx xx:xx:xx : pre-install completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : pre-wrapup starting
xxxx/xx/xx xx:xx:xx : pre-wrapup completed
xxxx/xx/xx xx:xx:xx : wrapup starting
xxxx/xx/xx xx:xx:xx : wrapup completed
xxxx/xx/xx xx:xx:xx : End Building testxx [default] (master)

====================== testxx/alt
xxxx/xx/xx xx:xx:xx : Building testxx [alt] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : alt-pre-setup starting
xxxx/xx/xx xx:xx:xx : alt-pre-setup completed
xxxx/xx/xx xx:xx:xx : alt-config starting
xxxx/xx/xx xx:xx:xx : alt-config completed
xxxx/xx/xx xx:xx:xx : alt-post-config starting
xxxx/xx/xx xx:xx:xx : alt-post-config completed
xxxx/xx/xx xx:xx:xx : pre-build [alt] starting
xxxx/xx/xx xx:xx:xx : pre-build [alt] completed
xxxx/xx/xx xx:xx:xx : build [alt] starting
xxxx/xx/xx xx:xx:xx : build [alt] completed
xxxx/xx/xx xx:xx:xx : post-build [alt] starting
xxxx/xx/xx xx:xx:xx : post-build [alt] completed
xxxx/xx/xx xx:xx:xx : pre-install [alt] starting
xxxx/xx/xx xx:xx:xx : pre-install [alt] completed
xxxx/xx/xx xx:xx:xx : alt-install starting
xxxx/xx/xx xx:xx:xx : alt-install completed
xxxx/xx/xx xx:xx:xx : alt-post-install starting
xxxx/xx/xx xx:xx:xx : alt-post-install completed
xxxx/xx/xx xx:xx:xx : pre-wrapup [alt] starting
xxxx/xx/xx xx:xx:xx : pre-wrapup [alt] completed
xxxx/xx/xx xx:xx:xx : alt-wrapup starting
xxxx/xx/xx xx:xx:xx : alt-wrapup completed
xxxx/xx/xx xx:xx:xx : alt-post-wrapup starting
xxxx/xx/xx xx:xx:xx : alt-post-wrapup completed
xxxx/xx/xx xx:xx:xx : End Building testxx [alt] (master)

@@@ ALT/CONFIG  testxx/xxx_xx-linux-gnu-alt/src
@@@ ALT/POST-CONFIG  testxx/xxx_xx-linux-gnu-alt/src
@@@ CONFIG  testxx/xxx_xx-linux-gnu-default/src
@@@ POST-CONFIG  testxx/xxx_xx-linux-gnu-default/src
@@@ ALT/PRE-SETUP  testxx
@@@ PRE-SETUP  testxx
@@@ BUILD  testxx/xxx_xx-linux-gnu-alt/src
@@@ POST-BUILD  testxx/xxx_xx-linux-gnu-alt/src
@@@ PRE-BUILD  testxx/xxx_xx-linux-gnu-alt/src
@@@ BUILD  testxx/xxx_xx-linux-gnu-default/src
@@@ POST-BUILD  testxx/xxx_xx-linux-gnu-default/src
@@@ PRE-BUILD  testxx/xxx_xx-linux-gnu-default/src
@@@ ALT/INSTALL  testxx/xxx_xx-linux-gnu-alt/src
@@@ POST-INSTALL  testxx/xxx_xx-linux-gnu-alt/src
@@@ PRE-INSTALL  testxx/xxx_xx-linux-gnu-alt/src
@@@ INSTALL  testxx/xxx_xx-linux-gnu-default/src
@@@ PRE-INSTALL  testxx/xxx_xx-linux-gnu-default/src
@@@ ALT/POST-WRAPUP  testxx
@@@ ALT/WRAPUP  testxx
@@@ PRE-WRAPUP  testxx
@@@ PRE-WRAPUP  testxx
@@@ WRAPUP  testxx
