xxxx/xx/xx xx:xx:xx : Building testxx [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : config starting
xxxx/xx/xx xx:xx:xx : config completed
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : skip global install
xxxx/xx/xx xx:xx:xx : End building testxx-default

xxxx/xx/xx xx:xx:xx : Building testxx [alt] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : config [alt] starting
xxxx/xx/xx xx:xx:xx : config [alt] completed
xxxx/xx/xx xx:xx:xx : build [alt] starting
xxxx/xx/xx xx:xx:xx : build [alt] completed
xxxx/xx/xx xx:xx:xx : install [alt] starting
xxxx/xx/xx xx:xx:xx : install [alt] completed
xxxx/xx/xx xx:xx:xx : copy install into ../local-install
xxxx/xx/xx xx:xx:xx : End building testxx-alt
