xxxx/xx/xx xx:xx:xx : Building lib1 [default] (v1.2)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : get sources from tar
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : tests starting
main
lib from tar
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building lib1 [default] (v1.2)

xxxx/xx/xx xx:xx:xx : Building lib1 [default] (v1.2)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : tests starting
main
lib from tar
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building lib1 [default] (v1.2)

xxxx/xx/xx xx:xx:xx : Building lib1 [default] (v1.2)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : tests starting
main
lib from tar
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building lib1 [default] (v1.2)
