==== no build expected
xxxx/xx/xx xx:xx:xx : Building libx-default (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building libx-default

==== purge and re-build
xxxx/xx/xx xx:xx:xx : Purging libx for xxx_xx-linux-gnu/default
xxxx/xx/xx xx:xx:xx : Building libx-default (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building libx-default

==== no build expected
xxxx/xx/xx xx:xx:xx : Building libx-default (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building libx-default

==== purge-only, no build expected
OK build directory present before purge
xxxx/xx/xx xx:xx:xx : Purging libx for xxx_xx-linux-gnu/default
OK build directory removed, only manifest found
==== re-build after purge
xxxx/xx/xx xx:xx:xx : Building libx-default (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building libx-default

