========== OPT-A
dependencies error building mcross/opta
error: cross-opta not found
========== OPT-B
dependencies error building mcross/optb
error: cross-optb not found
========== OPT-A + OPT-B
dependencies error building mcross/opta.optb
error: cross-opta not found
error: cross-optb not found
========== NO-OPT
dependencies error building mcross
error: cross-general not found

========== OPT-A
dependencies error building mcrossc/opta
error: crossc-common not found
error: crossc-opta not found
========== OPT-B
dependencies error building mcrossc/optb
error: crossc-common not found
error: crossc-optb not found
========== OPT-A + OPT-B
dependencies error building mcrossc/opta.optb
error: crossc-common not found
error: crossc-opta not found
error: crossc-optb not found
========== NO-OPT
dependencies error building mcrossc
error: crossc-common not found
error: crossc-general not found
