========= should fail
xxxx/xx/xx xx:xx:xx : Building checkvcs [default] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : error: cannot get sources from /this.is.path/some/dir

========= should be ok
xxxx/xx/xx xx:xx:xx : Building checkvcs [default] (master)
xxxx/xx/xx xx:xx:xx : native x86_64-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : End Building checkvcs [default] (master)
