=================== plan vx (libx:vx libx)
xxxx/xx/xx xx:xx:xx : need building libx, current version latest

xxxx/xx/xx xx:xx:xx : Building libx [default] (vx)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : tests starting
main
liba.D br_b
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building libx-default

xxxx/xx/xx xx:xx:xx : need building libx, current version latest

xxxx/xx/xx xx:xx:xx : Building libx [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : config starting
xxxx/xx/xx xx:xx:xx : config completed
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : tests starting
main
libb.B master (default)
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building libx-default

xxxx/xx/xx xx:xx:xx : Building mainmult [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : tests starting
main on master
liba.D br_b
libb.B master (default)
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building mainmult-default

=================== plan var (libx:vx libx/variantx:vx)
xxxx/xx/xx xx:xx:xx : need building libx, current version latest

xxxx/xx/xx xx:xx:xx : Building libx [default] (vx)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : tests starting
main
liba.A br_a
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building libx-default

xxxx/xx/xx xx:xx:xx : need building libx, current version latest

xxxx/xx/xx xx:xx:xx : Building libx [variantx] (vx.x)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : variantx-config starting
xxxx/xx/xx xx:xx:xx : variantx-config completed
xxxx/xx/xx xx:xx:xx : build [variantx] starting
xxxx/xx/xx xx:xx:xx : build [variantx] completed
xxxx/xx/xx xx:xx:xx : install [variantx] starting
xxxx/xx/xx xx:xx:xx : install [variantx] completed
xxxx/xx/xx xx:xx:xx : tests [variantx] starting
main
libb.B vx (variantx)
xxxx/xx/xx xx:xx:xx : tests [variantx] completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building libx-variantx

xxxx/xx/xx xx:xx:xx : Building mainmult [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : tests starting
main on master
liba.A br_a
libb.B vx (variantx)
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building mainmult-default

=================== second run plan var (no build)
xxxx/xx/xx xx:xx:xx : need building libx, current version latest

xxxx/xx/xx xx:xx:xx : Building libx [default] (vx)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : tests starting
main
liba.A br_a
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building libx-default

xxxx/xx/xx xx:xx:xx : need building libx, current version latest

xxxx/xx/xx xx:xx:xx : Building libx [variantx] (vx.x)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : tests [variantx] starting
main
libb.B vx (variantx)
xxxx/xx/xx xx:xx:xx : tests [variantx] completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building libx-variantx

xxxx/xx/xx xx:xx:xx : Building mainmult [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : tests starting
main on master
liba.A br_a
libb.B vx (variantx)
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building mainmult-default

=================== second run plan var (test-only)
xxxx/xx/xx xx:xx:xx : need building libx, current version latest

xxxx/xx/xx xx:xx:xx : Building libx [default] (vx)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : tests
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : tests starting
main
liba.A br_a
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building libx-default

xxxx/xx/xx xx:xx:xx : need building libx, current version latest

xxxx/xx/xx xx:xx:xx : Building libx [variantx] (vx.x)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : tests
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : tests [variantx] starting
main
libb.B vx (variantx)
xxxx/xx/xx xx:xx:xx : tests [variantx] completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building libx-variantx

xxxx/xx/xx xx:xx:xx : Building mainmult [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : tests
xxxx/xx/xx xx:xx:xx : no build needed, versions match
xxxx/xx/xx xx:xx:xx : tests starting
main on master
liba.A br_a
libb.B vx (variantx)
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End building mainmult-default
