xxxx/xx/xx xx:xx:xx : Building testx-default (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install tests wrapup
xxxx/xx/xx xx:xx:xx : get sources from mercurial
xxxx/xx/xx xx:xx:xx : config starting
xxxx/xx/xx xx:xx:xx : config completed
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : tests starting
hello scbi in mercurial
xxxx/xx/xx xx:xx:xx : tests completed
xxxx/xx/xx xx:xx:xx : End building testx-default

