xxxx/xx/xx xx:xx : Building libx-default
xxxx/xx/xx xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : get sources from git
xxxx/xx/xx xx:xx : build starting
xxxx/xx/xx xx:xx : build completed
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
liba.C master
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

xxxx/xx/xx xx:xx : Building libx-default
xxxx/xx/xx xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : get sources from git
xxxx/xx/xx xx:xx : build starting
xxxx/xx/xx xx:xx : build completed
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
liba.A br_a
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

xxxx/xx/xx xx:xx : Building libx-default
xxxx/xx/xx xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : get sources from git
xxxx/xx/xx xx:xx : build starting
xxxx/xx/xx xx:xx : build completed
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
liba.D br_b
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

xxxx/xx/xx xx:xx : Building libx-default
xxxx/xx/xx xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : get sources from tar
xxxx/xx/xx xx:xx : build starting
xxxx/xx/xx xx:xx : build completed
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
lib from tar
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

xxxx/xx/xx xx:xx : Building libx-default
xxxx/xx/xx xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx : steps : setup config build install tests
xxxx/xx/xx xx:xx : get sources from git
xxxx/xx/xx xx:xx : build starting
xxxx/xx/xx xx:xx : build completed
xxxx/xx/xx xx:xx : install starting
xxxx/xx/xx xx:xx : install completed
xxxx/xx/xx xx:xx : tests starting
main
liba.C master
xxxx/xx/xx xx:xx : tests completed
xxxx/xx/xx xx:xx : copy install into ../install

