mainlib:
xxxx/xx/xx xx:xx:xx : Building libx [titi] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : apply-patch filename libx-x-fix.patch
xxxx/xx/xx xx:xx:xx : build [titi] starting
xxxx/xx/xx xx:xx:xx : build [titi] completed
xxxx/xx/xx xx:xx:xx : install [titi] starting
xxxx/xx/xx xx:xx:xx : install [titi] completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building libx [titi] (master)

xxxx/xx/xx xx:xx:xx : Building mainlib [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : get sources from git
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building mainlib [default] (master)

mainlib and specific variant libx:
xxxx/xx/xx xx:xx:xx : Building libx [newtiti] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : apply-patch filename libx-x-fix.patch
xxxx/xx/xx xx:xx:xx : build [newtiti] starting
xxxx/xx/xx xx:xx:xx : build [newtiti] completed
xxxx/xx/xx xx:xx:xx : install [newtiti] starting
xxxx/xx/xx xx:xx:xx : install [newtiti] completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building libx [newtiti] (master)

xxxx/xx/xx xx:xx:xx : Building mainlib [default] (master)
xxxx/xx/xx xx:xx:xx : native xxx_xx-linux-gnu
xxxx/xx/xx xx:xx:xx : steps : setup config build install wrapup
xxxx/xx/xx xx:xx:xx : build starting
xxxx/xx/xx xx:xx:xx : build completed
xxxx/xx/xx xx:xx:xx : install starting
xxxx/xx/xx xx:xx:xx : install completed
xxxx/xx/xx xx:xx:xx : copy install into ../install
xxxx/xx/xx xx:xx:xx : End Building mainlib [default] (master)
