name: Check Commits

on:
  push:
    branch:
      - update-hook

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check commit
        run: |
          echo checked
          false
